apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "Dgraph.fullname" . }}
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ template "Dgraph.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      app: {{ template "Dgraph.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "Dgraph.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:

      - name: dgraph-ratel
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 8000
          hostPort: 8000
          name: ratel-http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - dgraph-ratel

      - name: zero
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 5080
          name: zero-grpc
        - containerPort: 6080
          name: zero-http
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - bash
          - "-c"
          - |
            set -ex
            {{ .Values.DgraphZero.command }}{{ .Values.config.DefaultHostName }}{{ .Values.DgraphZero.port }}

      - name: server
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - bash
          - "-c"
          - |
            set -ex
            dgraph server --my=0.0.0.0:7080 --lru_mb 2048 --zero 0.0.0.0:5080
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: server-http
        - containerPort: 9080
          name: server-grpc
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir

  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi