apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "Dgraph.fullname" . }}
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ template "Dgraph.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      app: {{ template "Dgraph.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "Dgraph.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:

      - name: dgraph-ratel
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.config.DgraphRatel_port }}
          hostPort: {{ .Values.config.DgraphRatel_port }}
          name: ratel-http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - {{ .Values.Ratel.command }}

      - name: zero
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.config.DgraphZero_port }}
          name: zero-grpc
        - containerPort: {{ .Values.config.DgraphZero_port_http }}
          name: zero-http
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - bash
          - "-c"
          - |
            set -ex
            {{ .Values.DgraphZero.command }}{{ .Values.config.DefaultHostName }}{{ .Values.config.DgraphZero_port }}

      - name: server
        image: dgraph/dgraph:latest
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        command:
          - bash
          - "-c"
          - |
            set -ex
            {{ .Values.DgraphServer.command }}{{ .Values.config.DefaultHostName }}{{ .Values.DgraphSeparator }}{{ .Values.config.DgraphZero_port }} {{ .Values.DgraphMemory }} {{ .Values.config.DgraphServer_memory }} {{ .Values.DgraphServer.commandtoZero }} {{ .Values.config.DefaultHostName }}{{ .Values.DgraphSeparator }}{{ .Values.config.DgraphZero_port }}
           # dgraph server --my=                      0.0.0.0                               :                              7080                              --lru_mb               2048                                      --zero                                       0.0.0.0                                  :                             5080
        ports:
        - containerPort: {{ .Values.config.DgraphServer_port_http }}
          hostPort: {{ .Values.config.DgraphServer_port_http }}
          name: server-http
        - containerPort: {{ .Values.config.DgraphServer_port }}
          name: server-grpc
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir

  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi