apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "Dgraph.fullname" . }}
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "Dgraph.fullname" . }}
            servicePort: 8000