apiVersion: v1
kind: Service
metadata:
  name: {{ template "Dgraph.fullname" . }}
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  ports:
  - port: 5080
    targetPort: 5080
    name: zero-grpc
  - port: 6080
    targetPort: 6080
    name: zero-http
  - port: 8080
    targetPort: 8080
    name: server-http
  - port: 9080
    targetPort: 9080
    name: server-grpc
  - port: 8000
    targetPort: 8000
    name: ratel-http
  selector:
    app: {{ template "Dgraph.name" . }}
status:
  loadBalancer: {}