{{- if .Values.service.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "Dgraph.fullname" . }}
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  rules:
  - host: {{ .Values.service.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "Dgraph.fullname" . }}
            servicePort: {{ .Values.config.DgraphRatel_port }}
#   tls:
#   - hosts:
#     - {{ .Values.service.ingress.host }}
# ---
{{- end }}