{{- if (.Values.service.loadBalancer.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "Dgraph.fullname" . }}-lb
  labels:
    app: {{ template "Dgraph.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.config.DgraphZero_port }}
    targetPort: {{ .Values.config.DgraphZero_port }}
    name: zero-grpc
    protocol: GRPC
  - port: {{ .Values.config.DgraphZero_port_http }}
    targetPort: {{ .Values.config.DgraphZero_port_http }}
    name: zero-http
    protocol: TCP
  - port: {{ .Values.config.DgraphAlpha_port_http }}
    targetPort: {{ .Values.config.DgraphAlpha_port_http }}
    name: alpha-http
    protocol: TCP
  - port: {{ .Values.config.DgraphAlpha_port }}
    targetPort: {{ .Values.config.DgraphAlpha_port }}
    name: alpha-grpc
    protocol: GRPC
  - port: {{ .Values.config.DgraphRatel_port }}
    targetPort: {{ .Values.config.DgraphRatel_port }}
    name: ratel-http
    protocol: TCP
  selector:
    app: {{ template "Dgraph.fullname" . }}
status:
  loadBalancer: {}
{{- end }}